insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정보화사업 예비타당성조사 제도');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	폭포수 모델');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	프로토타이핑 모델');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Spiral 모델');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	반복적 개발 모델');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	RAD(락스)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW 개발방법론');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	구조적 개발방법론');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정보공학(IE) 방법론');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	객체지향 프로그래밍 특징');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	캡슐화(encapsulation)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	추상화');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	다형성');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정보은닉(Information Hiding)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	상속성');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	객체지향 설계의 원리');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	객체지향 개발방법론');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	컴포넌트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	CBD');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Product Line');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	도메인 공학');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	요구 공학');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	요구사항');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	요구사항명세서');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	페르소나(persona)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	개발 방법론 테일러링(Tailoring)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	AOP');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Agile');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	XP');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SCRUM');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW 발주 프로세스 총정리');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	공공 소프트웨어 사업 제안 요청서 작성 가이드라인');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	제안평가, 기술성평가');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW 분리발주');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW 분할발주');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	품질성능 평가시험(BMT)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	소프트웨어 산업 진흥법');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	조달청 협상에 의한 계약 제안서평가 세부기준');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SOA');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ESB');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	웹서비스');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SRP/OCP/LSP/ISP/DIP');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW Architecture');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"ISO/IEC/IEEE 42010
(구 버전 IEEE1471)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW Architecture 평가');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ATAM');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	CBAM');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Architecture Driver');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	모델 / 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Blackboard pattern');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	4+1 View Model');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SAD');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	MSA');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	clean architecture');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW Architect');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	MDA');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	MDD');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Spring Framwork');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	7개 서비스 그룹/38개 서비스');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	버전별 차이점');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	UML의 관계(Relationship)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Stereotype');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Activity diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	State Machine diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	State Diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Usecase diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Sequence diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Class diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Component diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Composite Structure Diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Deployment diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Interaction diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Interaction overview Diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Timing Diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Communication Diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Feature diagram');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	UML 2.0 / 2.X 최종 확인');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	UML Profile');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	MOF');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	OCL');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	추상클래스');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	인터페이스(클래스)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"Design Pattern
(23개 패턴)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Hollywood Principle');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Abstract Factory 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Builder 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Prototype 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Singleton 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Factory method 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Adaptor 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Bridge 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Composite 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Decorator 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Façade 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Flyweight 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Proxy 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Chain of responsibility 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Command 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Mediator 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Memento 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Interpreter 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Iterator 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	State');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Strategy pattern');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Observer');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Template Method');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Visitor 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	MVC 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	TDD');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	코드 스멜');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	클린코드(Clean Code)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Code 유형');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	DevOps');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SRE(Site Reliability Engineering)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Test 일반');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	테스트 유형');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	테스트 차터');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	테스트 원리');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	V-Model');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	테스트베드(Testbed)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	테스트 단계 분류');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	테스트 정보 획득 분류');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	프로그램 실행여부');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	블랙박스 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	명세기반 테스팅 기법');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"화이트박스테스트
(White Box Test)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	구조기반테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	탐색적 테스팅');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	테스트 자동화');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Regression Test');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	테스트 오라클');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	MC/DC');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Crowdingsourcing Test');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Compliance Test');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	모델기반 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	경험기반 기법');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	뮤테이션 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	사용성 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	빅뱅테스트(Bigbang Test)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	패키지 소프트웨어 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Embedded System Test');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	지각테스팅');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	성능 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Back-to-back testing');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	PoC');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Pilot test');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"퍼즈 테스트(Fuzz Testing) Fuzzing"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	콘콜릭 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	튜링 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"Smoke Test(스모크 테스트)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	퍼지 이론(Fuzzy Theory)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"커서리 테스트(Cursory Test)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	예비(Sanity) 테스트');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	키워드 기반 테스팅');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Pairwise Testing');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	상태 전이 테스팅');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ABX test');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	BMT');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	카오스 테스트(Chaos Test)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Test Process');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ISO 29119');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ISO/IEC 33063');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Test case');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Test Coverage');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Test 결과보고서');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정보시스템 운영 성과관리');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정보시스템 운영 성과평가');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"Lehman 소프트웨어 변화(리만) 유지보수/유지관리 전체"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	모듈화');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Fan-out, Fan-in');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	3R');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Reuse');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	역공학(Reverse Engineering)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	재공학(Re-Engineering)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	소프트웨어 리팩토링');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW 유지보수');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	QM(품질관리)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	품질관리계획수립');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	품질보증(QA), 품질관리');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	품질통제(QC)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"ISO/IEC 25010(ISO 9126)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"ISO/IEC 25041(ISO 14598)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"ISO/IEC 25051 (ISO 12119)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ISO 25000(SQuaRE)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	품질 속성 시나리오');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ISO 12207');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	CMMI');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	CMMI 2.0');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	평가 기법(SCAMPI)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SPICE');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ASPICE(Automotive SPICE) (ISO/IEC 33020)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	GS 인증');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ISO 9000');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Peer-review(동료검토)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Six Sigma');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	QA');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	TMMi');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SP');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	McCabe의 회전 복잡도');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"Halstead 메트릭(할스테드)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ISO 14971');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	의료 기기 표준');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW 안정성 분석 개념');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	FTA(결함 트리 분석)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	FMEA');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	HAZOP');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	감리 지침 2개 참조');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Framework');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	감리 절차');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	수행시점');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	감리 조건');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	감리 산출물');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	감리결과보고서 작성하기');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	감리원 종류');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	오픈소스 소프트웨어');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	License');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	양립성');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	OSS 거버넌스');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	OSH');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW 비용 산정 일반');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	LOC 방법');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Man/Month');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Function Point / ISO/IEC 14143');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	간이법 계산');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정규법 계산');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"보정계수/애플리케이션 복잡도 보정계수"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW사업 대가산정 가이드');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	COCOMO I');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	COCOMO II');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	하드웨어 규모산정 3가지 방법');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	ISO/IEC19770-1');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Software Platform');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW개발 생산성 향상방안');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW 육성 방안');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW중심사회');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	소프트웨어 교육');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	난독화');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW Escrow');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	소스코드 저작권보호');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW Visualization');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SWEBOK');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW영향평가제');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	PBL');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	소프트웨어 산업 진흥법 (법률 제 12872호) 및 시행령 - BMT');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정적멤버와 Static');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Final 필드와 상수');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Final 클래스와 매소드');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	접근 제한');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	인터페이스');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	인터페이스 구현');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	"추상클래스(Abstract cless)"');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	함수형 언어/함수형 프로그래밍');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	SW사업정보저장소');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Python(파이썬) 언어');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	technical debt');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	Cleanroom software engineering');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	RUP');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정규식(Regular Expression)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	원격 프로스저 호출(RPC)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	로우코드(Low Code)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	민간투자형 SW 사업 PPP((PPP, Public Private Partnership)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	원격지 개발');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	서킷 브레이커(Circuit Breaker) 패턴');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	이너소스(Innersource)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	정형검증 (Formal Verification)');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	요구사항 상세화 실무 가이드라인');
insert into slackpush.exam (gubun,problem) values('OWO_TYPE','[문제]	IoC(Inversion of Control)');